### ISSUE TITLE
Custom build of new engine didn't work on OSx Mojave 10.14 with xCode 10.14

### ISSUE THREAD

**Issue by ikroni** [Gcenx/WineskinServer#20] opened 2019-09-12 11:55 UTC
I try to add new xCode to WineskinEngine build, but it still failed to checkin for gcc:
`checking build system type... x86_64-apple-darwin18.7.0
checking host system type... x86_64-apple-darwin18.7.0
checking whether make sets $(MAKE)... no
checking for gcc... gcc
checking whether the C compiler works... no
configure: error: in `/Users/a.anisimov/Downloads/wine-4.14':
configure: error: C compiler cannot create executables
See `config.log' for more details
An error occurred during Wine Configure, build halted.
Cleaning up changes made for the build, if any...`

**Comment by Gcenx** [comment] 2019-09-14 17:07
Duplicate of #7

**Closed by Gcenx** 2019-09-14 17:07 UTC
Labels: duplicate
